name: WolvenKit-Nightly
on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout github repo (+ download lfs dependencies)
      uses: actions/checkout@v2
    - name: Setup 7z with choco
      with: |
        choco install 7z -y
    - name: Download libs for irrlicht
      with: |
        cd cd $Env:GITHUB_WORKSPACE\\WolvenKit.Irrlicht\\
        wget https://outwa.it/lib.zip
        7z  -y x lib.zip
    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v1.0.5
      with:
        nuget-version: latest
    - name: Restore packages
      run: nuget restore WolvenKit.sln
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1
    - name: Build with MSBuild
      run: msbuild  WolvenKit.sln -p:Configuration=Release  -p:Platform=x64 -m
    - name: Zip Release
      run: |
        cd $Env:GITHUB_WORKSPACE\\WolvenKit\bin
        Compress-Archive -Path ./x64/Release/ -DestinationPath WolvenKit.zip
    - name: Deploy Nightly
      uses: Maxzor/deploy-nightly@v1.0.4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: https://uploads.github.com/repos/Traderain/Wolven-kit/releases/11743470/assets{?name,label}
        release_id: 11743470
        asset_path: WolvenKit\bin\WolvenKit.zip
        asset_name: WolvenKit-Nightly-$$.zip
        asset_content_type: application/zip
