name: WolvenKit-Nightly
on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check Nightly
      uses: Maxzor/check-nightly@v1.0.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_id: 11743470
        asset_name: WolvenKit-Nightly-$$.zip
        asset_content_type: application/zip
    - uses: actions/checkout@v1
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
    - name: Restore packages
      run: nuget restore WolvenKit.sln
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: Build with MSBuild
      run: msbuild  WolvenKit.sln -p:Configuration=Release
    - name: Zip Release
      run: |
        cd $Env:GITHUB_WORKSPACE\\WolvenKit\bin
        Compress-Archive -Path ./Release/ -DestinationPath WolvenKit.zip
    - name: Deploy Nightly
      uses: Maxzor/deploy-nightly@v1.0.4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: https://uploads.github.com/repos/Traderain/Wolven-kit/releases/11743470/assets{?name,label}
        release_id: 11743470
        asset_path: WolvenKit\bin\WolvenKit.zip
        asset_name: WolvenKit-Nightly-$$.zip
        asset_content_type: application/zip
