name: publish-nuget
on:
  workflow_dispatch:

jobs:   

  publish-nugets:
    runs-on: windows-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.x

    # Pack and upload nugets for Types, Modkit and CLI
    - run: dotnet pack .\WolvenKit.RED4\WolvenKit.RED4.csproj
    - name: RED4
      continue-on-error: true
      run: dotnet nuget push .\WolvenKit.RED4\nupkg\*.nupkg --api-key ${{secrets.NUGET_KEY}} --source "https://api.nuget.org/v3/index.json" --skip-duplicate

    - run: dotnet pack .\WolvenKit.Modkit\WolvenKit.Modkit.csproj
    - name: Modkit
      continue-on-error: true
      run: dotnet nuget push .\WolvenKit.Modkit\nupkg\*.nupkg --api-key ${{secrets.NUGET_KEY}} --source "https://api.nuget.org/v3/index.json" --skip-duplicate

    - run: dotnet pack .\WolvenKit.CLI\WolvenKit.CLI.csproj
    - name: CLI
      continue-on-error: true
      run: dotnet nuget push .\WolvenKit.CLI\nupkg\*.nupkg --api-key ${{secrets.NUGET_KEY}} --source "https://api.nuget.org/v3/index.json" --skip-duplicate
